import type { Tasks } from "@/types/Tasks.types";

export const TaskDto: Tasks[] = [
  {
    id: 1,
    title: "Design dashboard layout",
    project: "TaskFlow",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-09-18",
  },
  {
    id: 2,
    title: "Implement authentication",
    project: "TaskFlow",
    status: "todo",
    priority: "high",
    dueDate: "2026-09-20",
  },
  {
    id: 3,
    title: "Create project management API",
    project: "TaskFlow",
    status: "in-progress",
    priority: "medium",
    dueDate: "2026-09-22",
  },
  {
    id: 4,
    title: "Build responsive navigation",
    project: "Portfolio Website",
    status: "completed",
    priority: "medium",
    dueDate: "2026-09-15",
  },
  {
    id: 5,
    title: "Create portfolio hero section",
    project: "Portfolio Website",
    status: "completed",
    priority: "low",
    dueDate: "2026-09-14",
  },
  {
    id: 6,
    title: "Implement product listing",
    project: "E-Commerce App",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-09-19",
  },
  {
    id: 7,
    title: "Add shopping cart functionality",
    project: "E-Commerce App",
    status: "todo",
    priority: "medium",
    dueDate: "2026-09-24",
  },
  {
    id: 8,
    title: "Create blog post editor",
    project: "Blog Platform",
    status: "todo",
    priority: "low",
    dueDate: "2026-09-26",
  },
  {
    id: 9,
    title: "Add dark mode support",
    project: "TaskFlow",
    status: "completed",
    priority: "low",
    dueDate: "2026-09-12",
  },
  {
    id: 10,
    title: "Implement task filtering",
    project: "TaskFlow",
    status: "in-progress",
    priority: "medium",
    dueDate: "2026-09-21",
  },
];
