/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as dashboardProjectsProjectIdRouteImport } from './routes/(dashboard)/projects/$projectId'
import { Route as dashboardTaskIndexRouteImport } from './routes/(dashboard)/task/index'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardProjectsProjectIdRoute =
  dashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTaskIndexRoute = dashboardTaskIndexRouteImport.update({
  id: '/task/',
  path: '/task/',
  getParentRoute: () => dashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/projects/$projectId': typeof dashboardProjectsProjectIdRoute
  '/task/': typeof dashboardTaskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/register': typeof RegisterIndexRoute
  '/projects/$projectId': typeof dashboardProjectsProjectIdRoute
  '/task': typeof dashboardTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/(dashboard)/projects/$projectId': typeof dashboardProjectsProjectIdRoute
  '/(dashboard)/task/': typeof dashboardTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register/' | '/projects/$projectId' | '/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register' | '/projects/$projectId' | '/task'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/(dashboard)/'
    | '/register/'
    | '/(dashboard)/projects/$projectId'
    | '/(dashboard)/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/projects/$projectId': {
      id: '/(dashboard)/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof dashboardProjectsProjectIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/task/': {
      id: '/(dashboard)/task/'
      path: '/task'
      fullPath: '/task/'
      preLoaderRoute: typeof dashboardTaskIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardProjectsProjectIdRoute: typeof dashboardProjectsProjectIdRoute
  dashboardTaskIndexRoute: typeof dashboardTaskIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardProjectsProjectIdRoute: dashboardProjectsProjectIdRoute,
  dashboardTaskIndexRoute: dashboardTaskIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
